job/urls.py
# -*- encoding: utf-8 -*-
from django.urls import re_path

from .views import (
    CandidateListView,
    CandidateUpdateProfileView,
    CandidateUpdateView,
    cv_download,
    JobApplicationDetailView,
    JobBasketDetailView,
    JobCreateView,
    JobCreditCreateView,
    JobCreditDetailView,
    JobCreditMarkPaidView,
    JobDeleteView,
    JobDetailView,
    JobElasticSearchView,
    JobLatestView,
    JobListView,
    JobLocationAjaxView,
    JobLocationRegionAjaxView,
    JobPublishView,
    JobSearchView,
    JobUndeleteView,
    JobUpdateView,
    LandingPageCreateView,
    LandingPageListView,
    LandingPageUpdateView,
    RecruiterUpdateProfileView,
    RecruiterUpdateView,
)


urlpatterns = [
    re_path(
        r"^list/(?P<job_feed_pk>\d+)/$",
        JobListView.as_view(),
        name="job.list",
    ),
    re_path(
        r"elastic/search/$",
        JobElasticSearchView.as_view(),
        name="job.elastic.search",
    ),
    re_path(r"^latest/$", JobLatestView.as_view(), name="job.latest"),
    re_path(r"search/$", JobSearchView.as_view(), name="job.search"),
    re_path(
        r"^(?P<pk>\d+)/delete/$",
        JobDeleteView.as_view(),
        name="job.delete",
    ),
    re_path(
        r"^(?P<pk>\d+)/undelete/$",
        JobUndeleteView.as_view(),
        name="job.undelete",
    ),
    re_path(
        r"^application/(?P<pk>\d+)/$",
        JobApplicationDetailView.as_view(),
        name="job.application.detail",
    ),
    re_path(r"^(?P<pk>\d+)/$", JobDetailView.as_view(), name="job.detail"),
    re_path(
        r"^landing/$",
        LandingPageListView.as_view(),
        name="job.landing.page.list",
    ),
    re_path(
        r"^landing/create/$",
        LandingPageCreateView.as_view(),
        name="job.landing.page.create",
    ),
    re_path(
        r"^landing/update/(?P<pk>\d+)/$",
        LandingPageUpdateView.as_view(),
        name="job.landing.page.update",
    ),
    re_path(
        r"^location/$",
        JobLocationAjaxView.as_view(),
        name="job.location",
    ),
    re_path(
        r"^location/region/$",
        JobLocationRegionAjaxView.as_view(),
        name="job.location.region",
    ),
    re_path(
        r"^checkout/basket/(?P<pk>\d+)/$",
        JobBasketDetailView.as_view(),
        name="job.checkout.basket.detail",
    ),
    re_path(
        r"^checkout/job-credit/(?P<pk>\d+)/$",
        JobCreditDetailView.as_view(),
        name="job.checkout.credit.detail",
    ),
    re_path(
        r"^job-credit/(?P<pk>\d+)/create/$",
        JobCreditCreateView.as_view(),
        name="job.credit.create",
    ),
    re_path(
        r"^job-credit/(?P<pk>\d+)/paid/$",
        JobCreditMarkPaidView.as_view(),
        name="job.credit.mark-paid",
    ),
    re_path(
        r"^(?P<pk>\d+)/publish/$",
        JobPublishView.as_view(),
        name="job.publish",
    ),
    re_path(
        r"^(?P<pk>\d+)/update/$",
        JobUpdateView.as_view(),
        name="job.update",
    ),
    re_path(
        r"^candidate/(?P<pk>\d+)/update/$",
        CandidateUpdateView.as_view(),
        name="job.candidate.update",
    ),
    re_path(
        r"^candidate/(?P<pk>\d+)/profile/update/$",
        CandidateUpdateProfileView.as_view(),
        name="job.candidate.profile.update",
    ),
    re_path(
        r"^candidate/list/$",
        CandidateListView.as_view(),
        name="job.candidate.list",
    ),
    re_path(r"^cv/download/(?P<pk>\d+)/$", cv_download, name="job.cv.download"),
    re_path(
        r"^recruiter/(?P<pk>\d+)/update/$",
        RecruiterUpdateView.as_view(),
        name="job.recruiter.update",
    ),
    re_path(
        r"^recruiter/(?P<pk>\d+)/profile/update/$",
        RecruiterUpdateProfileView.as_view(),
        name="job.recruiter.profile.update",
    ),
    re_path(
        r"^recruiter/(?P<pk>\d+)/job/create/$",
        JobCreateView.as_view(),
        name="job.recruiter.job.create",
    ),
]

job/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.apps import apps
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils import timezone
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

from base.form_utils import (
    RequiredFieldForm,
    set_widget_required,
    FileDropInput,
)
from gdpr.forms import ConsentFieldFormMixin
from login.forms import UserUsernameCreationForm
from .models import (
    Candidate,
    CV,
    CVType,
    Job,
    JobApplication,
    JobRole,
    JobBasket,
    JobCredit,
    LandingPage,
    Location,
    Recruiter,
    Experience,
)


LAST_LOGIN_CHOICES = (
    (3, "3 Months"),
    (6, "6 Months"),
    (12, "12 Months"),
    (0, "12 Months+"),
)

SEARCH_TYPE_CHOICES = (
    ("position", "Position (exclude Candidates without a CV)"),
    ("mailshot", "Mailshot (include Candidates without a CV)"),
)


class LandingPageCreateForm(forms.ModelForm):
    name = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"class": "pure-input-2-3"})

    class Meta:
        model = LandingPage
        fields = ("name", "location", "job_role", "practice_area")


class LandingPageForm(forms.ModelForm):
    class Meta:
        model = LandingPage
        fields = ("location", "job_role", "practice_area")


class LocationLookupForm(forms.Form):
    """Form for doing location search."""

    RADIUS_CHOICES = [
        # (None,  ''),
        (5, "5 miles"),
        (10, "10 miles"),
        (25, "25 miles"),
        (50, "50 miles"),
        (100, "100 miles"),
        (999, "Unlimited"),
    ]

    area = forms.CharField(max_length=200, required=False)
    radius = forms.ChoiceField(choices=RADIUS_CHOICES, required=False)

    code = forms.CharField(max_length=30)
    # data type of region or postcode (depending on 'autocomplete' selection)
    data_type = forms.CharField(max_length=30)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["code"].widget = forms.HiddenInput()
        self.fields["data_type"].widget = forms.HiddenInput()
        self.fields["area"].widget.attrs.update(
            {"class": "autocomplete pure-input-2-3"}
        )
        self.fields["radius"].widget.attrs.update({"class": "pure-input-2-3"})
        self.fields["area"].label = "Postcode or Town"
        self.fields["radius"].label = "Radius"

    def clean(self):
        area = self.cleaned_data.get("area")
        data_type = self.cleaned_data.get("data_type")
        code = self.cleaned_data.get("code")

        if data_type and code:
            pass
        elif area:
            raise ValidationError(
                "Please select a valid postcode or region. To select a "
                "postcode (or region) start typing the postcode (or region) "
                "and then click on the correct entry from the list"
            )
        return self.cleaned_data

    class Meta:
        fields = ("postcode", "radius")


class CVForm(RequiredFieldForm):
    """Form for CV."""

    contact = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        cv_type_id = kwargs.pop("cv_type_id", 0)
        contact_id = kwargs.pop("contact_id", 0)
        super(CVForm, self).__init__(*args, **kwargs)
        for name in ("file_name", "cv_type"):
            self.fields[name].widget.attrs.update({"class": "pure-input-2-3"})
        self.fields["file_name"].label = "Upload CV"
        if contact_id:
            self.fields["contact"].widget = forms.HiddenInput()
            self.fields["contact"].initial = contact_id
            self.fields["contact"].label = ""
        if cv_type_id:
            self.fields["cv_type"].widget = forms.HiddenInput()
            self.fields["cv_type"].initial = cv_type_id
            self.fields["cv_type"].label = ""
        else:
            # flakes - undefined name 'CVType'
            self.fields["cv_type"] = forms.ChoiceField(
                choices=[(o.id, o.name) for o in CVType.objects.all()],
                label="CV Type",
            )

        self.fields["file_name"].widget = FileDropInput(
            default_text="Drop your CV here...",
            click_text="or click here to select your CV",
        )

    class Meta:
        model = CV
        fields = ("file_name", "contact", "title", "cv_type")


class CandidateForm(RequiredFieldForm):
    """Form for Candidate (uses the 'Contact' model)."""

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super(CandidateForm, self).__init__(*args, **kwargs)
        for name in (
            "title",
            "first_name",
            "last_name",
            "email",
            "address_1",
            "address_2",
            "address_3",
            "town",
            "county",
            "country",
            "postcode",
        ):
            self.fields[name].widget.attrs.update({"class": "pure-input-2-3"})
        for name in (
            "title",
            "first_name",
            "last_name",
            "email",
            "address_1",
            "town",
            "county",
            "country",
            "postcode",
        ):
            set_widget_required(self.fields[name])
        for name in ("phone", "mobile"):
            self.fields[name].widget.attrs[
                "placeholder"
            ] = "Either a phone or mobile number is required"

    def clean(self):
        phone = self.cleaned_data.get("phone")
        mobile = self.cleaned_data.get("mobile")
        if phone or mobile:
            pass
        else:
            raise ValidationError("Please enter a phone or mobile number.")
        return self.cleaned_data

    class Meta:
        model = apps.get_model(settings.CONTACT_MODEL)
        fields = (
            "title",
            "first_name",
            "last_name",
            "phone",
            "mobile",
            "email",
            "address_1",
            "address_2",
            "address_3",
            "town",
            "county",
            "country",
            "postcode",
        )


class CandidateCreateForm(
    ConsentFieldFormMixin, CandidateForm, UserUsernameCreationForm
):
    """Form for Candidate."""

    notify_checkbox = forms.BooleanField(required=False)
    newsletter_checkbox = forms.BooleanField(required=False)
    search_checkbox = forms.BooleanField(required=False)
    data_checkbox = forms.BooleanField(required=False)
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    def __init__(self, *args, **kwargs):
        self.data_consent = kwargs.pop("data_consent")
        self.newsletter_consent = kwargs.pop("newsletter_consent")
        self.notify_consent = kwargs.pop("notify_consent")
        self.search_consent = kwargs.pop("search_consent")
        super().__init__(*args, **kwargs)
        for name in ("username", "password1", "password2"):
            self.fields[name].widget.attrs.update({"class": "pure-input-2-3"})

        self._setup_checkbox("notify_checkbox", self.notify_consent)
        self._setup_checkbox("search_checkbox", self.search_consent)
        self._setup_checkbox("newsletter_checkbox", self.newsletter_consent)
        self._setup_checkbox("data_checkbox", self.data_consent)

    def clean_data_checkbox(self):
        return self._clean_checkbox("data_checkbox", self.data_consent)

    def clean_notify_checkbox(self):
        return self._clean_checkbox("notify_checkbox", self.notify_consent)

    def clean_newsletter_checkbox(self):
        return self._clean_checkbox(
            "newsletter_checkbox", self.newsletter_consent
        )

    def clean_search_checkbox(self):
        return self._clean_checkbox("search_checkbox", self.search_consent)

    class Meta:
        model = apps.get_model(settings.CONTACT_MODEL)
        fields = (
            "title",
            "first_name",
            "last_name",
            "phone",
            "mobile",
            "email",
            "address_1",
            "address_2",
            "address_3",
            "town",
            "county",
            "country",
            "postcode",
            "username",
            "password1",
            "password2",
        )


class CandidateProfileForm(
    ConsentFieldFormMixin, LocationLookupForm, RequiredFieldForm
):
    # consents
    notify_checkbox = forms.BooleanField(required=False)
    search_checkbox = forms.BooleanField(required=False)
    newsletter_checkbox = forms.BooleanField(required=False)

    # used to validate if user has cv
    next_url = None
    user_name = None

    upload_cv = forms.FileField(
        label="Upload a new CV",
        help_text="You must upload a cv to apply for a job",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.notify_consent = kwargs.pop("notify_consent")
        self.search_consent = kwargs.pop("search_consent")
        self.newsletter_consent = kwargs.pop("newsletter_consent")
        self.updating_my_own_profile = kwargs.pop("updating_my_own_profile")
        self.user_name = kwargs.pop("user_name", None)
        self.next_url = kwargs.pop("next", None)
        super().__init__(*args, **kwargs)

        self.fields["job_experience"].label = "Experience"
        self.fields["job_experience"].help_text = ""
        self.fields["job_experience"].required = True
        self.fields["job_experience"].queryset = Experience.objects.display()
        self.fields["area"].label = "I'm based in"
        self.fields["radius"].label = "Looking for work within"

        # not required
        self.fields["code"].required = False
        self.fields["data_type"].required = False

        # widget

job/templates/job/_admin_menu.html
<li class="pure-menu-item{% if '/job/' in path %} pure-menu-selected{% endif %}">
  <a href="{% url 'job.candidate.list' %}" class="pure-menu-link">
    <i class="fa fa-group fa-fw"></i>
    Jobs Board
  </a>
</li>

job/templates/job/_candidate_applications.html
{% if user.is_staff or user.contact.is_candidate %}
  {% if user.is_staff %}
  <div class="sectionHeading">Candidate's Applications:</div>
  {% else %}
  <div class="sectionHeading">Your Applications:</div>
  {% endif %}
  <div class="job">
    <div class="jobLine">
      <div class="three cols columnHeading">Job title</div>
      <div class="two cols columnHeading">Publish Date</div>
      <div class="two cols columnHeading">Apply Date</div>
      <div class="one cols columnHeading">CV </div>
    </div>

    {% for application in o.jobapplication_set.all %}
      <div class="jobLine">
        <div class="three cols">
          <a href="{% url job_application_detail_url_name application.pk %}">
            {{ application.job.title }}
          </a>
        </div>
        <div class="two cols">
        {{ application.job.publish_date }}
        </div>
        <div class="two cols">
          {% if application.apply_date %}
            {{ application.apply_date }}
          {% else %}
            Not submitted
          {% endif %}
        </div>
        <div class="one cols">
          {% if application.cv %}
            <a href="{% url candidate_cv_view_url_name application.candidate.pk application.pk %}">View</a>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
  {% if user.is_staff %}
    <div class="jobLine">
      <div class="sectionHeading">Candidate's Clicks on Feed Links:</div>
    </div>
    <div class="job">
      <div class="jobLine">
        <div class="six cols columnHeading">Job title</div>
        <div class="two cols columnHeading">Click Date</div>
      </div>

      {% for click in o.jobtracking_set.all %}
        <div class="jobLine">
          <div class="six cols">
            {{ click.job.title }}
          </div>
          <div class="two cols">
            {{ click.created|date:"d/m/Y" }}
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endif %}

job/templates/job/_candidate_clicks.html
<table class="pure-table pure-table-bordered" width="100%">
  <thead>
    <tr valign="top">
      <th>Job Title</th>
      <th>Click Date</th>
      <th>No. Apply Clicks</th>
      <th>No. Views</th>
    </tr>
  </thead>
  {% for click in contact.candidate.jobtracking_set.all %}
    <tr valign="top">
      <td>
        <a href="{% url 'job.detail' click.job.pk %}">
          {{ click.job.title }}
        </a>
      </td>
      <td>
        {{ click.click_date|date:"d/m/Y" }}
      </td>
      <td>
        {{ click.application_click_count }}
      </td>
      <td>
        {{ click.view_count }}
      </td>
    </tr>
  {% endfor %}
</table>

job/templates/job/_candidate_looking_for_work.html
{% if candidate.job_location_radius == 999 %}
  UK wide
{% elif not candidate.location %}
  {{ candidate.contact.town }}{% if candidate.contact.town and candidate.contact.county %}, {% endif %}{{ candidate.contact.county }}
{% elif candidate.job_location_radius %}
  within {{ candidate.job_location_radius}} miles of {{ candidate.location }}
{% else %}
  in {{ candidate.location }}
{% endif %}

job/templates/job/_jobcredit_total_price.js.html
<script>
Number.prototype.formatMoney = function(precision, dec_point, thou_sep){
  var n = this,
  precision = isNaN(c = Math.abs(precision)) ? 2 : precision,
  dec_point = dec_point == undefined ? "." : dec_point,
  thou_sep = thou_sep == undefined ? "," : thou_sep,
  s = n < 0 ? "-" : "",
  i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))),
  j = (j = i.length) > 3 ? j % 3 : 0;
 return s + (j ? i.substr(0, j) + thou_sep : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thou_sep) + (precision ? dec_point + Math.abs(n - i).toFixed(precision).slice(2) : "");
};
  function display_price() {
    var discount_threshold = {{ discount_threshold }};
    var standard_price = {{ standard_price }};
    var discount_price = {{ discount_price }};
    var number_of_credits = parseInt($('#id_credits').val());
    var total_price = 0.0;
    if (number_of_credits > discount_threshold) {
      total_price = number_of_credits * discount_price;
    } else {
      total_price = number_of_credits * standard_price;
    }
    formatted = '£' + total_price.formatMoney();
    if (number_of_credits > 0)
      formatted += " + VAT";
    // alert(formatted);
    $('#id_total_price').text(formatted);
    return total_price;
  }
  $("#id_credits").change(display_price);
  $("#id_credits").keypress(display_price);
  display_price();
</script>

job/templates/job/_location.html
{% load thumbnail %}
<div class="pure-g">
  <div class="pure-u-1">
    <h3>
      {% if user.is_staff %}
       <a href="{% url 'job.location.update' o.pk %}">
         <i class="fa fa-edit"></i>
         {{ o.title }}
        </a>
      {% else %}
        {% if o.url %}
          <a href="{{ o.url }}" target="_blank">
            {{ o.title }}
          </a>
        {% else %}
          {{ o.title }}
        {% endif %}
      {% endif %}
    </h3>
    {% if o.url %}
      <a href="{{ o.url }}" target="_blank">
        {{ o.url }}
      </a>
    {% endif %}
    {% autoescape off %}
      {{ o.description }}
    {% endautoescape %}
  </div>
</div>
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-2">
    {% if o.address %}
      {{ o.address|linebreaksbr }}
    {% endif %}
    {% if o.url_map %}
      <br />
      <br />
      <a href="{{ o.url_map }}" target="_blank">
        <i class="fa fa-external-link"></i>
        Click here for a map....
      </a>
    {% endif %}
  </div>
  <div class="pure-u-1 pure-u-md-1-2">
    {% if o.url %}
      <a href="{{ o.url }}" target="_blank">
    {% endif %}
    {% if o.picture %}
      <img class="pure-img" src="{% thumbnail o.picture 150x150 crop %}" />
    {% endif %}
    {% if o.url %}
      </a>
    {% endif %}
  </div>
</div>

job/templates/job/_settings.html
<div class="pure-g">
  <div class="pure-u-1">
    <h4>Job</h4>
  </div>
</div>
<div class="pure-g">
  {% if user.is_staff %}
    <div class="pure-u-1 pure-u-md-1-4">
      <div class="l-box">
        <a href="{% url 'job.landing.page.list' %}">
          <i class="fa fa-calendar"></i>
          Landing Pages
        </a>
      </div>
    </div>
    <div class="pure-u-1 pure-u-md-1-4">
      <div class="l-box">
        <a href="{% url 'job.location.list' %}">
          <i class="fa fa-calendar"></i>
          Locations
        </a>
      </div>
    </div>
  {% endif %}
</div>

job/templates/job/base.html
{% extends 'dash/base.html' %}

job/templates/job/candidate_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Candidate
{% endblock sub_title %}

{% block sub_heading %}
  Candidate
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        {% include '_form.html' with legend=legend multipart=True %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block script_extra %}
  {% include 'job/_editor.html' %}
  <script type="text/javascript">
    $(function(){
        $('#id_area').on('click', function(){ $(this).select(); }); 
    });

    function set_radius_enabled() {
        if($('#id_data_type').val() == "postcode") {
            $('#id_radius').prop('disabled', false);
        } else {
            $('#id_radius').prop('disabled', true);
        }
    }
    set_radius_enabled();
    // https://github.com/devbridge/jQuery-Autocomplete 
    $('.autocomplete').autocomplete({
        minChars: 2,
        serviceUrl: '{% url 'job.location.region' %}',
        onInvalidateSelection: function () {
            console.log("onInvalidateSelection");
            $('#id_data_type').val("");
            $('#id_code').val("");
            $('#id_radius').prop('disabled', true);
        },
        onSelect: function (suggestion) {
            $('#id_data_type').val(suggestion.data.data_type);
            $('#id_code').val(suggestion.data.code);
            set_radius_enabled();
        }
    });
  </script>
{% endblock script_extra %}

job/templates/job/checkout_basket_detail.html
{% extends 'dash/base.html' %}
{% load static %}

{% block sub_title %}
  Checkout Detail
{% endblock sub_title %}

{% block sub_heading %}
  Checkout Detail
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <br>
      <table class="pure-table pure-table-bordered">
        <tbody>
          <tr valign="top">
            <td>Recruiter</td>
            <td>
              <a href="{% url 'contact.detail' object.recruiter.contact.pk %}">
                {{ object.recruiter.full_name }}
              </a>
            </td>
          </tr>
          <tr valign="top">
            <td>Checkout Status</td>
            <td><strong>{{ object.checkout_state.name }}</strong></td>
          </tr>
          {% for item in object.jobbasketitem_set.all %}
            <tr valign="top">
              <td>Job Title</td>
              <td>
                <a href="{% url 'job.detail' item.job.pk %}">
                  {{ item.job.title }}
                </a>
              </td>
            </tr>
            <tr valign="top">
              <td>Date Posted</td>
              <td>{{ item.job.publish_date|date:'d/m/Y H:i:s' }}</td>
            </tr>
            <tr valign="top">
              <td>Price</td>
              <td>{{ item.product.price }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <br>
      {% include 'checkout/_checkout_list.html' with object_list=checkout_audit %}
    </div>
  </div>
{% endblock content %}

job/templates/job/job_confirm_delete.html
{% extends "job/base.html" %}

{% block sub_title %}
  Delete job
{% endblock sub_title %}

{% block sub_heading %}
  Delete job
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        {% include 'job/_job.html' with j=job %}
        {% include '_form.html' with legend='Are you sure you want to delete this job' submit='Delete' %}
      </div>
    </div>
  </div>
{% endblock content %}

job/templates/job/job_confirm_publish.html
{% extends "job/base.html" %}

{% block sub_title %}
  Publish job
{% endblock sub_title %}

{% block sub_heading %}
  Publish job
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        <form action="" method="post">{% csrf_token %}
          <p>
            Are you sure you want to publish this job?
          </p>
          {% include 'job/_job.html' with j=job %}
          <br />
          <br />
          <input type="submit" value="Publish" class="pure-button pure-button-primary" />
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

job/templates/job/job_search.html
{% extends 'job/base.html' %}
{% load static %}

{% block stylesheets_extra %}
  <link rel="stylesheet" href="{% static 'job/css/job.css' %}">
{% endblock stylesheets_extra %}

{% block sub_title %}
  Job Search
{% endblock sub_title %}

{% block sub_heading %}
  Job Search
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-open pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_back_to_dash.html' %}
          {% if user.is_staff %}
          {% include 'job/_admin_top_menu.html' %}
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
        <form action="." id="search_form" method="get" enctype="multipart/form-data" class="pure-form pure-form-aligned" xclass="pure-form-stacked">
          {% csrf_token %}
          {% if form.non_field_errors %}
            {{ form.non_field_errors }}
          {% endif %}
          <fieldset>
            {% for field in form.visible_fields %}
              <div class="pure-control-group">
                {% if field.label %}
                  <label for='{{ field.id_for_label }}'>{{ field.label }}{% if field.help_text %} - {{ field.help_text }}{% endif %}:</label>
                {% endif %}
                {{ field }}
                {% for error in field.errors %}
                    <span class="errorlist"><mark>{{ error }}</mark></span>
                {% endfor %}
              </div>
            {% endfor %}
            <div class="pure-controls">
              <p>
                <input type="button" onclick="submitJobFormWithPage()" value="Search" class="pure-button pure-button-primary" />
              </p>
            </div>
          </fieldset>
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
          {% endif %}
        </form>
    </div>
  </div>
  {% include 'job/_paginate_temp.html' %}
  <table class="pure-table pure-table-bordered">
    <thead>
      <tr>
        <th>Recruiter</th>
        <th>Job</th>
        <th>Published</th>
        <th>Closing</th>
      </tr>
    </thead>
    {% for job in job_list %}
      <tr valign="top">
        <td>
          <a href="{% url 'contact.detail' job.recruiter.contact.pk %}">
            {{ job.recruiter.contact.company_name }}
          </a>
        </td>
        <td>
          <a href="{% url 'job.detail' job.pk %}">
            {{ job.title }}
          </a>
          <br />
          {{ job.location_name }}
        </td>
        <td>
          {% if job.publish_date %}
            {{ job.publish_date|date:"d/m/Y" }}
          {% else %}
            Not Published
          {% endif %}
        </td>
        <td>
          {{ job.close_date|date:"d/m/Y" }}
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="4">No jobs posted yet</td>
      </tr>
    {% endfor %}
  </table>
  {% include 'job/_paginate_temp.html' %}
{% endblock content %}

{% block script %}
  {{ block.super }}
  <script type="text/javascript">
    $(function(){
        $('#id_area').on('click', function(){ $(this).select(); }); 
    });

    function set_radius_enabled() {
        if($('#id_data_type').val() == "postcode") {
            $('#id_radius').prop('disabled', false);
        } else {
            $('#id_radius').prop('disabled', true);
        }
    }
    set_radius_enabled();
    // https://github.com/devbridge/jQuery-Autocomplete 
    $('.autocomplete').autocomplete({
        minChars: 2,
        serviceUrl: '{% url 'job.location.region' %}',
        onInvalidateSelection: function () {
            console.log("onInvalidateSelection");
            $('#id_data_type').val("");
            $('#id_code').val("");
            $('#id_radius').prop('disabled', true);
        },
        onSelect: function (suggestion) {
            $('#id_data_type').val(suggestion.data.data_type);
            $('#id_code').val(suggestion.data.code);
            set_radius_enabled();
        }
    });
  </script>
{% endblock script %}